sudo: required
services: 
  - docker

before_install:
  - docker build -t nehsus/k8boiler -f Dockerfile.dev .

script:
  - docker run nehsus/k8boiler npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "k8boiler"
  env: "K8boiler-env"
  bucket_name: "elasticbeanstalk-us-east-2-065455708008"
  bucket_path: "k8boiler"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"